### ISSUE TITLE
PROJECT SETTING FAILURE

### ISSUE THREAD

**Issue by FIFTYSIXFACTORY** [markmal/freeship-plus-in-lazarus#32] opened 2018-02-18 19:00 UTC
Hi,
in PROJECT>Project settings>Mains dimensions when you split from Imperial to Meters thye model dimensions are not kept .Same problem when you rescale the hull, dimensions are not updated.
For example when you switch a 33.33ft hull (imperial) to meters ,the lenght became 33.33m instead of 10.1590m.
rgds

**Comment by markmal** [comment] 2018-02-20 01:12
Hi,

currently I am busy with another project, I'll take a look into this 
when will have time.

Thanks for using FreeShip!
Mark

**Comment by FIFTYSIXFACTORY** [comment] 2018-02-20 19:35
Hi,
No problem, it was just for information.
Thanks for your great job!

Rgds
Julien

----- Mail original -----
De: "Mark Malakanov" <notifications@github.com>
À: "markmal/freeship-plus-in-lazarus" <freeship-plus-in-lazarus@noreply.github.com>
Cc: "FIFTYSIXFACTORY" <fiftysixfactory@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 20 Février 2018 02:12:25
Objet: Re: [markmal/freeship-plus-in-lazarus] PROJECT SETTING FAILURE (#32)

Hi, 

currently I am busy with another project, I'll take a look into this 
when will have time. 

Thanks for using FreeShip! 
Mark

**Comment by markmal** [comment] 2019-05-22 12:31
the problem is fixed in release 4.1.1.159

**Closed by markmal** 2019-05-22 12:31 UTC
